
var TRIGGEREVENT_ENTERSCENE = 0;
var TRIGGEREVENT_LEAVESCENE = 1;
var TRIGGEREVENT_INITSCENE = 2;
var TRIGGEREVENT_UPDATESCENE = 3;
var TRIGGEREVENT_TOUCHBEGAN = 4;
var TRIGGEREVENT_TOUCHMOVED = 5;
var TRIGGEREVENT_TOUCHENDED = 6;
var TRIGGEREVENT_TOUCHCANCELLED = 7;