/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_cocos2dx_lib_Cocos2dxJavascriptJavaBridge */

#ifndef _Included_org_cocos2dx_lib_Cocos2dxJavascriptJavaBridge
#define _Included_org_cocos2dx_lib_Cocos2dxJavascriptJavaBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_cocos2dx_lib_Cocos2dxJavascriptJavaBridge
 * Method:    callJavascriptFunctionWithString
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_cocos2dx_lib_Cocos2dxJavascriptJavaBridge_evalString
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
